# Plot4
household <- read.table("./household_power_consumption.txt", header = TRUE, sep = ";", colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"), na.strings = "?")
household$DateTime <- paste(household$Date, household$Time)
household$DateTime <- strptime(household$DateTime, format = "%d/%m/%Y %H:%M:%S")
household$DateTime <- as.POSIXct(household$DateTime)
household$Date <- as.Date(household$Date, format = "%d/%m/%Y")
library(dplyr)
household.clean <- filter(household, household$Date == "2007-02-01" | household$Date == "2007-02-02")

png(file="./plot4.png",width=480,height=480)
par(mfcol = c(2,2), mar = c(4, 4, 1, 1), oma = c(0, 0, 0, 0))
plot(household.clean$DateTime, household.clean$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "",  cex.axis = 0.7, cex.lab = 0.7)
plot(household.clean$DateTime,household.clean$Sub_metering_1, type = "n", ylab  = "Energy sub metering", xlab = "", cex.axis = 0.7, cex.lab = 0.7)
lines(household.clean$DateTime,household.clean$Sub_metering_1)
lines(household.clean$DateTime,household.clean$Sub_metering_2, col="red")
lines(household.clean$DateTime,household.clean$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), lwd=c(2.5,2.5, 2.5),col=c("black","red","blue"), cex = 0.50)
plot(household.clean$DateTime, household.clean$Voltage, type = "l", xlab = "datetime", ylab = "Voltaje", cex.axis = 0.7, cex.lab = 0.7)
plot(household.clean$DateTime, household.clean$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power", cex.axis = 0.7, cex.lab = 0.7)
dev.off()
