# Plot3
household <- read.table("./household_power_consumption.txt", header = TRUE, sep = ";", colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"), na.strings = "?")
household$DateTime <- paste(household$Date, household$Time)
household$DateTime <- strptime(household$DateTime, format = "%d/%m/%Y %H:%M:%S")
household$DateTime <- as.POSIXct(household$DateTime)
household$Date <- as.Date(household$Date, format = "%d/%m/%Y")
library(dplyr)
household.clean <- filter(household, household$Date == "2007-02-01" | household$Date == "2007-02-02")

png(file="./plot3.png",width=480,height=480)
plot(household.clean$DateTime,household.clean$Sub_metering_1, type = "n", ylab  = "Energy sub metering", xlab = "")
lines(household.clean$DateTime,household.clean$Sub_metering_1)
lines(household.clean$DateTime,household.clean$Sub_metering_2, col="red")
lines(household.clean$DateTime,household.clean$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), lwd=c(2.5,2.5, 2.5),col=c("black","red","blue"),, cex = 0.70)
dev.off()